### ISSUE TITLE
Definitions...

### ISSUE THREAD

**Issue by pottertech** [obokaman-com/stock-forecast#1]
How do you define the Short, Medium and Long term (time frames) that your program is providing in the output?

**Comment by obokaman-com** [comment]
Hi @pottertech. It depends on the time magnitude. When you're using "days", short term takes 7 days, mid term takes 15 days and long term takes 30 days. When you're using "hours", long term is 24 hours, mid term 12 hours and short term 6 hours. Finally, when you're using minutes, long term is 60 minutes, mid term 30 minutes and short term 15 minutes.

You can find the definition of these periods at:

https://github.com/obokaman-com/stock-forecast/blob/bf0dc5ba6b9be7723495112c607e19fb68b08cda/src/StockForecast/Domain/Model/Date/Period.php#L5-L28
